CONFIG_NR_CPUS := 8
CONFIG_LOG2_CPU_CACHELINE_SIZE := 6
CONFIG_LOG2_CPU_PAGE_SIZE := 12

CPPFLAGS_CONFIG = \
	-DCONFIG_LOG2_CPU_CACHELINE_SIZE=$(CONFIG_LOG2_CPU_CACHELINE_SIZE) \
	-DCONFIG_LOG2_CPU_PAGE_SIZE=$(CONFIG_LOG2_CPU_PAGE_SIZE)
